name: CI - Build and Test

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Grant Gradle execute permission
        run: chmod +x ./gradlew

      - name: Validate formatting (spotlessCheck)
        run: ./gradlew spotlessCheck

      - name: Run unit tests
        run: ./gradlew test

      - name: Generate test report summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: '**/build/reports/tests/test'
