name: CI - Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant Gradle execute permission
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build -x test -x spotbugsTest -x spotbugsMain

      - name: Validate formatting (spotlessCheck)
        run: ./gradlew spotlessCheck

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant Gradle execute permission
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Generate test report summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: '**/build/reports/tests/test'

  static-analysis:
    name: Static analysis
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant Gradle execute permission
        run: chmod +x ./gradlew

      - name: Run SpotBugs analysis
        run: ./gradlew spotbugsMain spotbugsTest

      - name: Generate SpotBugs reports summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-reports
          path: '**/build/reports/spotbugs/**/*.html'
